title: Blog on Creating blogs
author: SG
email: asunda25@asu.edu
description: > # this means to ignore newlines until "baseurl:"
  Error: Description not valid
 /* Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  */
# social links
github_username: arvinthSG

show_excerpts: true # set to false to remove excerpts on the homepage

theme: Minima
